### ISSUE TITLE
google-home: "traits" as in hardillb's web-interface

### ISSUE THREAD

**Issue by bastl** [vivereSmartGroup/node-red-contrib-viveresmartgroup-knxultil#6]
In the web-interface for node-red-google-home-assistant as provided by @hardillb one can activate various "traits" for the devices. For example I can add both "switch" and "brightness" and "colour" to a "light-device".

Currently, I have to copy paste a lot 

Perhaps one could have multiple in&outputs for the various communication objects of a dimming actor.

Output 1:  KNX-Datatype (e.g. 1.001)
Output 2:  KNX-Datatype (e.g. 5.001)

Input 1: Google
Input 2: Alexa
Input 3: Dashboard-UI
etc.

**Comment by vivereSmartGroup** [comment]
as I do not work so often with google assistant, just let me clarify if I well understood....
google messages comes with both on/off and brightness level, correct?
so, the tool should have 2 out pins for both bool and percentage, correct?

can you please post an example of what google sends? 
Thanks

**Comment by vivereSmartGroup** [comment]
Hello Bastl,
currently, node-red doesn't allow to add more than one input to any node, so we must stick with that, sorry!
